### PR TITLE
Make Diver a callable function

### PR DESCRIPTION
**Pull request by gavinking**
Hi, I might be missing something, but I could not see any obvious easy way to call this package as a function (at least not from C).

If that's correct, it makes it very difficult to embed it in another program.

This PR illustrates how that could be fixed.

Thanks!

### CODE REVIEW

**Comment by patscott** [comment]
It's already a callable function, it just has return type `void`.  The way to get the results out is to use the callback pointer `context`, which gives you maximum flexibility to define what you want out, when you want it and in what format. This is how it is embedded in e.g. https://github.com/gambitbsm/gambit_2.2.  

Having said that, there is some merit in also having a simple return signature for the best fit as you propose, for simpler applications. This is breaking in terms of the API though, so I will have to have a closer look at implications beyond the PR before approving.

**Comment by gavinking** [comment]
Well, sure, you can _call it,_ but AFAICT, there's no way to actually get a *return value* out of it without going and writing and reading and parsing text files!

I'm not suggesting that you merge this PR as-is, it's just intended to illustrate the point that if I want to use Diver in a larger program then what I want to do is:

- pass it a function to optimize and some parameters and 
- get a minimum back as a return value.

OTOH, what I probably don't want this function to do is a bunch of IO as a side effect. If I want to do IO, I want to manage that in my own program, not have a library function do it for me. And I definitely don't want to parse text files. :)

**Comment by gavinking** [comment]
> The way to get the results out is to use the callback pointer `context`, which gives you maximum flexibility to define what you want out, when you want it and in what format. 

Well, OK, granted, I might have missed something there, but that's because this parameter is:

1. almost undocumented, as far as I can see, aside from the cryptic comment:

   > !context pointer, used for passing info from the caller to likelihood/prior
   
   which doesn't seem to indicate that this is useful for obtaining the final result of the algorithm (the final `BF%vectors(1,:)`/`BF%values(1)`),
2. declared of type `void**` and `type(c_ptr)` (which gives no useful information about its type signature), and
3. used once in the examples, where I find it used in the following way:

   ```c++
   typedef double (*likelihood)(double[], const int, int&, bool&, const bool); // This example's internal standard likelihood function signature

   ...

   likelihood minus_lnlike;
   if (argc > 1 and strcmp(argv[1], "shell") == 0) minus_lnlike = gauss_shell; else minus_lnlike = &gauss;
   void* context = &minus_lnlike;

   ...
   ```

   This example doesn't obviously have anything to do with getting a final `BF` value out of `cdiver()`, so it's not at all clear how I would use `context` for that. And so I think I can be forgiven for missing the fact that it was intended to be used in this way.

_Whatever,_ receiving a `void**` pointer can't possibly be the usual way for a C function to return its result, and it's definitely not ergonomic for the user, so I recommend providing a way to just receive the `BF%vectors(1,:)`/`BF%values(1)` directly.

**Comment by patscott** [comment]
Yes sure, no need to lecture -- I accepted your feedback already that this sort of signature would be helpful for the subset of users who consider only the BF to be the result.  Other users consider different combinations of the samples and info about them to be the result though.  Also known and on the todo list to make I/O optional and to document the context pointer further.

**Comment by gavinking** [comment]
OK, great!

**Comment by patscott** [comment]
Closed as obsolete following merge of #6.

**Pull request closed without merging**
